// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BXT3HDm7s5xnG5xGPNAz7F0oj9TJnb0',
    appId: '1:976201997091:web:9aa23d4ad3afc01f58ca96',
    messagingSenderId: '976201997091',
    projectId: 'motion-track-81e04',
    authDomain: 'motion-track-81e04.firebaseapp.com',
    storageBucket: 'motion-track-81e04.firebasestorage.app',
    measurementId: 'G-FKY0WQXHK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFjBu4xKz3h9sJOKH4M5BtTRi-8cKHy2s',
    appId: '1:976201997091:android:491d68ec1bb44a9058ca96',
    messagingSenderId: '976201997091',
    projectId: 'motion-track-81e04',
    storageBucket: 'motion-track-81e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWqSs4lppgommvKG0M5oQAF6NnRDN1dX4',
    appId: '1:976201997091:ios:1686fb788e22f1e758ca96',
    messagingSenderId: '976201997091',
    projectId: 'motion-track-81e04',
    storageBucket: 'motion-track-81e04.firebasestorage.app',
    iosBundleId: 'com.example.motiontrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWqSs4lppgommvKG0M5oQAF6NnRDN1dX4',
    appId: '1:976201997091:ios:1686fb788e22f1e758ca96',
    messagingSenderId: '976201997091',
    projectId: 'motion-track-81e04',
    storageBucket: 'motion-track-81e04.firebasestorage.app',
    iosBundleId: 'com.example.motiontrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-BXT3HDm7s5xnG5xGPNAz7F0oj9TJnb0',
    appId: '1:976201997091:web:ec6021479ce4244658ca96',
    messagingSenderId: '976201997091',
    projectId: 'motion-track-81e04',
    authDomain: 'motion-track-81e04.firebaseapp.com',
    storageBucket: 'motion-track-81e04.firebasestorage.app',
    measurementId: 'G-49HX4Y9QG3',
  );
}
